spring:
  application:
    name: worklog
  datasource:
    generate-unique-name: false
    name: worklog
    url: jdbc:postgresql://127.0.0.1:5432/worklog
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 80MB
      max-request-size: 80MB

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

jwt:
  secret: labububabyj0hnprostoesh1k1abububabyjohnprost0eshiklabububabyj0hnprostoeshik
  lifetime: 1200000

api:
  giga-chat-api: ${GIGACHAT_API}